"""order_update_date

Revision ID: 635cfdcc9ad4
Revises: 55acabad906c
Create Date: 2023-08-29 02:04:49.722192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635cfdcc9ad4'
down_revision: Union[str, None] = '55acabad906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_order', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_order', 'update_date')
    # ### end Alembic commands ###
